name: Publish to edge

on:
  push:
    branches:
      - main
      - track/*

jobs:
  publish-to-edge:
    uses: canonical/operator-workflows/.github/workflows/publish_charm.yaml@main
    secrets: inherit
    strategy:
      matrix:
        charm: [postfix-relay]
    with:
      channel: 3/edge
      identifier: ${{ matrix.charm }}
      working-directory: './${{ matrix.charm }}-operator'
